package postgres

func ValidateSimpleType(typeStr string) bool {
	_, ok := types[typeStr]
	return ok
}

func ValidateArrayType(typeStr string) bool {
	_, ok := arrayTypes[typeStr]
	return ok
}

func ValidatePrecisionType(typeStr string, p, s int) bool {
	_, ok := precisionTypes[typeStr]
	return ok
}


var types = map[string]string{
	"bigint":                      "bigint",
	"int8":                        "bigint",
	"bigserial":                   "bigserial",
	"serial8":                     "bigserial",
	"bit":                         "bit",
	"bit varying":                 "bit varying",
	"varbit":                      "bit varying",
	"boolean":                     "boolean",
	"bool":                        "boolean",
	"box":                         "box",
	"bytea":                       "bytea",
	"character":                   "character",
	"char":                        "character",
	"character varying":           "character varying",
	"varchar":                     "character varying",
	"cidr":                        "cidr",
	"circle":                      "circle",
	"date":                        "date",
	"double precision":            "double precision",
	"float8":                      "double precision",
	"float":                       "double precision",
	"inet":                        "inet",
	"integer":                     "integer",
	"int":                         "integer",
	"int4":                        "integer",
	"interval":                    "interval",
	"json":                        "json",
	"jsonb":                       "jsonb",
	"line":                        "line",
	"lseg":                        "lseg",
	"macaddr":                     "macaddr",
	"macaddr8":                    "macaddr8",
	"money":                       "money",
	"numeric":                     "numeric",
	"decimal":                     "numeric",
	"path":                        "path",
	"pg_lsn":                      "pg_lsn",
	"pg_snapshot":                 "pg_snapshot",
	"point":                       "point",
	"polygon":                     "polygon",
	"real":                        "real",
	"float4":                      "real",
	"smallint":                    "smallint",
	"int2":                        "smallint",
	"smallserial":                 "smallserial",
	"serial2":                     "smallserial",
	"serial":                      "serial",
	"serial4":                     "serial",
	"text":                        "text",
	"time":                        "time",
	"timetz":                      "time with time zone",
	"time with time zone":         "time with time zone",
	"time without time zone":      "time",
	"timestamp":                   "timestamp",
	"timestamptz":                 "timestamp with time zone",
	"timestamp with time zone":    "timestamp with time zone",
	"timestamp without time zone": "timestamp",
	"tsquery":                     "tsquery",
	"tsvector":                    "tsvector",
	"txid_snapshot":               "txid_snapshot",
	"uuid":                        "uuid",
	"xml":                         "xml",
}

var arrayTypes = map[string]string{
	"bigint":                      "bigint",
	"int8":                        "bigint",
	"bigserial":                   "bigserial",
	"serial8":                     "bigserial",
	"bit":                         "bit",
	"bit varying":                 "bit varying",
	"varbit":                      "bit varying",
	"boolean":                     "boolean",
	"bool":                        "boolean",
	"box":                         "box",
	"bytea":                       "bytea",
	"character":                   "character",
	"char":                        "character",
	"character varying":           "character varying",
	"varchar":                     "character varying",
	"cidr":                        "cidr",
	"circle":                      "circle",
	"date":                        "date",
	"double precision":            "double precision",
	"float8":                      "double precision",
	"float":                       "double precision",
	"inet":                        "inet",
	"integer":                     "integer",
	"int":                         "integer",
	"int4":                        "integer",
	"interval":                    "interval",
	"json":                        "json",
	"jsonb":                       "jsonb",
	"line":                        "line",
	"lseg":                        "lseg",
	"macaddr":                     "macaddr",
	"macaddr8":                    "macaddr8",
	"money":                       "money",
	"numeric":                     "numeric",
	"decimal":                     "numeric",
	"path":                        "path",
	"pg_lsn":                      "pg_lsn",
	"pg_snapshot":                 "pg_snapshot",
	"point":                       "point",
	"polygon":                     "polygon",
	"real":                        "real",
	"float4":                      "real",
	"smallint":                    "smallint",
	"int2":                        "smallint",
	"smallserial":                 "smallserial",
	"serial2":                     "smallserial",
	"serial":                      "serial",
	"serial4":                     "serial",
	"text":                        "text",
	"time":                        "time",
	"timetz":                      "time with time zone",
	"time with time zone":         "time with time zone",
	"time without time zone":      "time",
	"timestamp":                   "timestamp",
	"timestamptz":                 "timestamp with time zone",
	"timestamp with time zone":    "timestamp with time zone",
	"timestamp without time zone": "timestamp",
	"tsquery":                     "tsquery",
	"tsvector":                    "tsvector",
	"txid_snapshot":               "txid_snapshot",
	"uuid":                        "uuid",
	"xml":                         "xml",
}

var precisionTypes = map[string]string{
	"bit":                         "bit",
	"bit varying":                 "bit varying",
	"varbit":                      "bit varying",
	"character":                   "character",
	"char":                        "character",
	"character varying":           "character varying",
	"varchar":                     "character varying",
	"numeric":                     "numeric",
	"decimal":                     "numeric",
	"float":                       "double precision",
	"time":                        "time",
	"timetz":                      "time with time zone",
	"time with time zone":         "time with time zone",
	"time without time zone":      "time",
	"timestamp":                   "timestamp",
	"timestamptz":                 "timestamp with time zone",
	"timestamp with time zone":    "timestamp with time zone",
	"timestamp without time zone": "timestamp",
	"interval":                    "interval",
}
